from typing import Any, Iterable, Mapping, Protocol


class SocialPlatformPort(Protocol):
    def create_post(self, submolt: str, title: str, content: str) -> str: ...
    def create_comment(self, post_id: str, content: str, parent_id: str | None = None) -> str: ...
    def delete_post(self, post_id: str) -> None: ...
    def fetch_feed(self, endpoint: str) -> Iterable[Mapping[str, Any]]: ...
    def search(self, query: str, limit: int = 20) -> Iterable[Mapping[str, Any]]: ...
